# Generated by Django 5.1.1 on 2024-09-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('problem', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
